# Generated by Django 4.1.3 on 2022-11-24 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APITEST', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='Crypto',
        ),
    ]
