# Generated by Django 4.1.3 on 2022-11-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APITEST', '0002_rename_people_crypto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto',
            old_name='country',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='crypto',
            old_name='name',
            new_name='cryptocurrency',
        ),
    ]
